apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: be
  name: be
spec:
  replicas: 10
  selector:
    matchLabels:
      app: be
  template:
    metadata:
      labels:
        app: be
    spec:
      containers:
      - image: fsedano/be:0.16
        name: be
      - image: jaegertracing/jaeger-agent
        name: jaegeragent
        args:
          - --reporter.grpc.host-port=dns:///simplest-collector-headless.observability:14250
          - --reporter.type=grpc

---
apiVersion: v1
kind: Service
metadata:
  name: be
spec:
  selector:
    app: be
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000